### ISSUE TITLE
Installing TensorFlow

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#1]
* Markdown文件：[Installing TensorFlow](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/index.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 翻译积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领
