### ISSUE TITLE
Distributed TensorFlow

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#100]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/deploy/distributed.md)
  * PR 地址：#148

  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by filosfino** [comment]
翻译认领

**Comment by leviding** [comment]
@filosfino ok

**Comment by filosfino** [comment]
#148 翻译完成

**Comment by leviding** [comment]
赞
