### ISSUE TITLE
How to run TensorFlow on Hadoop

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#101]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/deploy/hadoop.md)
  * PR 地址：#150
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by SallyGo** [comment]
翻译认领

**Comment by leviding** [comment]
@SallyGo 好的

**Comment by filosfino** [comment]
校对认领

**Comment by leviding** [comment]
@filosfino 好的，下次记得在对应的  pull request 下认领哈
