### ISSUE TITLE
A Tool Developer's Guide to TensorFlow Model Files

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#103]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/tool_developers/index.md)
  * PR 地址：#141
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
申请翻译

**Comment by leviding** [comment]
@pkuwwt  赞

**Comment by pkuwwt** [comment]
这个我翻译完了呀 @leviding
