### ISSUE TITLE
Adding a Custom Filesystem Plugin

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#104]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/add_filesys.md)
  * PR 地址：#151
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jasonxia23** [comment]
认领翻译

**Comment by leviding** [comment]
@jasonxia23 ok
