### ISSUE TITLE
Adding a New Op

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#105]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/adding_an_op.md)
  * PR 地址：#154
  ----
  * 翻译时间：14 天
  * 校对时间：3 天
  * 翻译积分：15 分
  * 校对积分：5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@pkuwwt 好的 👍

**Comment by leviding** [comment]
@pkuwwt 翻译的怎么样啦

**Comment by San-greal** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@San-greal 好的，下次记得在对应的 pull request 下认领
