### ISSUE TITLE
TensorFlow Architecture

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#106]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/architecture.md)
  * PR 地址：#118
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by leviding** [comment]
@changkun ok

**Comment by pkuwwt** [comment]
@leviding 校对申请

**Comment by filosfino** [comment]
校对认领

**Comment by leviding** [comment]
@filosfino 在对应的 pull request 下进行校对认领，而且本文校对认领够了哈，欢迎认领其他文章
