### ISSUE TITLE
Creating Estimators in tf.estimator

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#107]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/estimators.md)
  * PR 地址：#153
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领，妈蛋，怎么都那么长。。。

**Comment by leviding** [comment]
@edvardHua 好的，哈哈

**Comment by leviding** [comment]
@edvardHua 翻译怎么样啦

**Comment by edvardHua** [comment]
这两天提交

**Comment by leviding** [comment]
@edvardHua 好，辛苦啦

**Comment by edvardHua** [comment]
[PR153](https://github.com/xitu/tensorflow/pull/153)

之前翻译过一篇 Estimator 使用的分支是 `create_estimator`

翻译这篇时忘记新建分支了。
