### ISSUE TITLE
TensorFlow in other languages

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#109]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/language_bindings.md)
  * PR 地址：#152
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by leviding** [comment]
@changkun 辛苦啦

**Comment by leviding** [comment]
@changkun 翻译的怎么样啦

**Comment by changkun** [comment]
尴尬了.... 本来安排了时间周末一定提交的... 结果被加班了 T_T 我错了..

**Comment by leviding** [comment]
@changkun 哈哈哈哈，好
