### ISSUE TITLE
Custom Data Readers

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#110]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/new_data_formats.md)
  * PR 地址：#159
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
@leviding 翻译认领，看明天能不能搞完

**Comment by leviding** [comment]
@JohnJiangLA ok

**Comment by leviding** [comment]
@JohnJiangLA 这篇怎么样啦

**Comment by JohnJiangLA** [comment]
今晚弄好，耽误了，sorry，押尾了....

**Comment by leviding** [comment]
好滴，辛苦啦
