### ISSUE TITLE
Broadcasting semantics

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#125]
* Markdown文件：[Broadcasting semantics](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/broadcasting.md)
  * PR 地址：#155
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@pkuwwt 辛苦啦
