### ISSUE TITLE
Developing a new backend for XLA

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#126]
* Markdown文件：[Developing a new backend for XLA](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/developing_new_backend.md)
  * PR 地址：#156
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@pkuwwt 好的
