### ISSUE TITLE
XLA Overview

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#127]
* Markdown文件：[XLA Overview](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/index.md)
  * PR 地址：
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
@leviding 翻译申请
