### ISSUE TITLE
Using JIT Compilation

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#128]
* Markdown文件：[Using JIT Compilation](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/jit.md)
  * PR 地址：#157
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wzy816** [comment]
@leviding 认领翻译

**Comment by leviding** [comment]
@wzy816 ok
