### ISSUE TITLE
Operation Semantics

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#129]
* Markdown文件：[Operation Semantics](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/operation_semantics.md)
  * PR 地址：#158
  ----
  * 翻译时间：10 天
  * 校对时间：4 天
  * 翻译积分：20 分
  * 校对积分：8 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by liaodalin19903** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@liaodalin19903 好的

**Comment by leviding** [comment]
@liaodalin19903 别忘了哈这篇

**Comment by liaodalin19903** [comment]
不会，只是这篇比较长希望多给点时间。

发自我的 iPhone

**Comment by leviding** [comment]
@liaodalin19903 好，确实比较长，按照你的时间来就行，辛苦了 👍 ❤️

**Comment by leviding** [comment]
@liaodalin19903 怎么样啦

**Comment by liaodalin19903** [comment]
还有1/10， 只有一点了，今晚上弄完！不好意思哦。

**Comment by leviding** [comment]
@liaodalin19903 好的，这篇很长，辛苦了 😘
