### ISSUE TITLE
Shapes and Layout

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#130]
* Markdown文件：[Shapes and Layout](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/shapes.md)
  * PR 地址：#141
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
翻译申请

**Comment by leviding** [comment]
@pkuwwt 好的

**Comment by pkuwwt** [comment]
翻译完，只是PR好像不太对劲，麻烦 @leviding 确认一下
另外我认为这一节内容有错误，还要和校对人员核实一下

**Comment by pkuwwt** [comment]
原文没错，是我自己看走眼了 !== @leviding
