### ISSUE TITLE
Using AOT compilation

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#131]
* Markdown文件：[Using AOT compilation](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/xla/tfcompile.md)
  * PR 地址：#160
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jasonxia23** [comment]
认领翻译

**Comment by leviding** [comment]
@jasonxia23 ok

**Comment by leviding** [comment]
@jasonxia23 翻译的怎么样啦

**Comment by leviding** [comment]
@jasonxia23 进度怎么样啦

**Comment by jasonxia23** [comment]
@leviding 周末完成~

**Comment by leviding** [comment]
@jasonxia23 进度怎么样啦
