### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#132]
* Markdown文件：[Benchmarks](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/benchmarks.md)
  * PR 地址：
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by charsdavy** [comment]
认领翻译 @leviding

**Comment by leviding** [comment]
@charsdavy ok
