### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#133]
* Markdown文件：[Performance](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/index.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 翻译积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@lsvih

**Comment by lsvih** [comment]
认领翻译
