### ISSUE TITLE
Performance Guide

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#134]
* Markdown文件：[Performance Guide](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/performance_guide.md)
  * PR 地址：#146
  ----
  * 翻译时间：10 天
  * 校对时间：4 天
  * 翻译积分：16 分
  * 校对积分：6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
翻译申请 @leviding

**Comment by leviding** [comment]
@pkuwwt 好的，辛苦啦

**Comment by pkuwwt** [comment]
@leviding 翻译完毕
