### ISSUE TITLE
High-Performance Models

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#135]
* Markdown文件：[High-Performance Models](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/performance_models.md)
  * PR 地址：#147
  ----
  * 翻译时间：10 天
  * 校对时间：4 天
  * 翻译积分：12 分
  * 校对积分：5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by windhaunting** [comment]
@leviding 认领翻译

**Comment by leviding** [comment]
@windhaunting ok

**Comment by windhaunting** [comment]
@leviding 翻译完毕。
