### ISSUE TITLE
How to Quantize Neural Networks with TensorFlow

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#136]
* Markdown文件：[How to Quantize Neural Networks with TensorFlow](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/performance/quantization.md)
  * PR 地址：#149
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by windhaunting** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@windhaunting ok

**Comment by windhaunting** [comment]
@leviding  翻译完毕
