### ISSUE TITLE
MNIST For ML Beginners

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#16]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/mnist/beginners.md)
  * PR 地址：#63
  ----
  * 翻译时间：10 天
  * 校对时间：4 天
  * 翻译积分：12 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by vuuihc** [comment]
@leviding 认领翻译

**Comment by leviding** [comment]
好的 @vuuihc

**Comment by vuuihc** [comment]
翻译完成 https://github.com/xitu/tensorflow/pull/63 @leviding

**Comment by vuuihc** [comment]
@leviding 这个是不是没加积分

**Comment by leviding** [comment]
@vuuihc 嗯嗯，我看了是没加，我今天加上，另外多给两个积分补偿。有空继续翻译别的吧
