### ISSUE TITLE
TensorFlow Mechanics 101

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#17]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/mnist/mechanics.md)
  * PR 地址：#65
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bobmayuze** [comment]
申请翻译

**Comment by leviding** [comment]
@bobmayuze 好的
