### ISSUE TITLE
Deep MNIST for Experts

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#18]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/mnist/pros.md)
  * PR 地址：#39
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领

**Comment by leviding** [comment]
好的 @
