### ISSUE TITLE
Installing TensorFlow for C

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#2]
* Markdown文件：[Installing TensorFlow for C](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/install_c.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：1.5 分
  * 校对积分：0.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by luffydream** [comment]
认领翻译。

**Comment by leviding** [comment]
好的，翻以前认真看下规范 https://github.com/xitu/gold-miner/wiki

**Comment by leviding** [comment]
@luffydream 翻译的怎么样啦

**Comment by luffydream** [comment]
我已经翻译完了。但是上次PR失败了。所以晚上我再PR一下。

**Comment by leviding** [comment]
@好的，如果有哪里不会，教程里有写

**Comment by leviding** [comment]
@luffydream 还是没 PR 出来吗？教程有写，可以看

**Comment by luffydream** [comment]
我自己之前有fork过tensorflow。然后我fork xitu/tensorflow之后，显示的一直都是那个目录，这个要怎么办？

**Comment by luffydream** [comment]
我现在直接PR，一直是在那个tensorflow/tensorflow上面

**Comment by leviding** [comment]
还是没好。。。

**Comment by luffydream** [comment]
要不我把文档发给你，你来PR一下。因为我这边有fork过tensorflow，所以这个PR每次都会到那个上面。

**Comment by luffydream** [comment]
# Installing TensorFlow for C

TensorFlow在 [`c_api.h`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h)中定义了一套 C API,用来提供适合于[建立和其他语言的绑定](https://www.tensorflow.org/extend/language_bindings).
这套API倾向于简单性和一致性，而不是方便。

## 支持的平台

你可能会在下面的操作系统上安装用于C的TensorFlow:
  * Linux
  * Mac OS X


## 安装
采取下面几步来安装用于C的TensorFlow库，然后打开用于C的TensorFlow：
  1.选择你将会仅仅运行用于C的TensoFlow在CPU(S)上，还是有GPU(S)的帮助。为了帮你做出选择，在以下指南中阅读这一节，标题为“决定安装哪个TensorFlow”：
       * @{$install_linux#determine_which_tensorflow_to_install$Installing TensorFlow on Linux}
       * @{$install_mac#determine_which_tensorflow_to_install$Installing TensorFlow on Mac OS}

  2.通过调用下面的shell命令，下载并且解压TensorFlow的C库到`/usr/local/lib`：
         TF_TYPE="cpu" # Change to "gpu" for GPU support
         OS="linux" # Change to "darwin" for Mac OS
         TARGET_DIRECTORY="/usr/local"
         curl -L \
           "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-${OS}-x86_64-1.4.0-rc0.tar.gz" |
           sudo tar -C $TARGET_DIRECTORY -xz

`tar` 命令会解压TensorFlow C库到`TARGET_DIRECTORY`的子目录 `lib`中 . 比如指定 `/usr/local`作为`TARGET_DIRECTORY`,那么 `tar`就会解压TensorFlow C库到`/usr/local/lib`.

如果你更希望解压库到不同的目录，那么相应的调整`TARGET_DIRECTORY`

  3.在上一步中，如果你指定了一个系统目录(比如,`/usr/local`)作为`TARGET_DIRECTORY`, 然后运行`ldconfig`配置链接器.
  比如:
  <pre><b>sudo ldconfig</b></pre>
  如果你指定了一个 `TARGET_DIRECTORY`而不是系统目录, (比如, `~/mydir`)，那么你必须设定你的解压目录(比如, `~/mydir/lib`) 到两个环境变量中。
  比如:
  <pre> <b>export LIBRARY_PATH=$LIBRARY_PATH:~/mydir/lib</b> # For both Linux and Mac OS X
  <b>export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/mydir/lib</b> # For Linux only
  <b>export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:~/mydir/lib</b> # For Mac OS X only</pre>

## 验证你的安装
在安装完成之后，新建文件，输入以下代码，文件命名为`hello_tf.c`:
```c
#include <stdio.h>
#include <tensorflow/c/c_api.h>

int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}
```

### 编译和运行

调用以下命令来编译 `hello_tf.c`
<pre><b>gcc hello_tf.c</b></pre>
运行生成的可执行文件应该输出以下消息:
<pre><b>a.out</b>
Hello from TensorFlow C library version <i>number</i></pre>

### 定位问题
如果程序编译失败，最有可能的错误是`gcc`找不到TensorFlow C库.解决这个问题的方法是为`gcc`指定`-I` 和 `-L`选项.比如,`TARGET_LIBRARY`是`/usr/local`, 你应该这样调用`gcc`: 

<pre><b>gcc -I/usr/local/include -L/usr/local/lib hello_tf.c -ltensorflow</b></pre>

如果执行`a.out`失败,你就要问问自己这几个问题了:
  * 这个程序编译有没有错误？
  * 是否按第三步 [安装](#安装), 指定了正确的环境变量的目录?
  * 是否有正确的`export`这些环境变量?

如果你仍然会有编译或者运行的错误信息, 请到[StackOverflow](www.stackoverflow.com/questions/tagged/tensorflow)寻找或者请求可能的解决方案.

**Comment by leviding** [comment]
这次就我弄了，之后这种问题需要自己解决。因为我这每天几十个 PR，还有几十个 Issue，没有那么多时间处理。

翻译的时候注意几点格式问题，例如中英文、数字与字母之间的空格，全文中的中英文标点符号问题等等。还有空行断行问题，在 [翻译计划以这教程](https://github.com/xitu/gold-miner/wiki) 里都有详细的规定，这次我就挨个改了，以后要注意。

**Comment by luffydream** [comment]
好的。太麻烦你了，我下次都自己解决好。主要是我刚刚fork过tensorflow/tensorflow,才导致这个PR每次都会到那个上面。

**Comment by leviding** [comment]
嗯嗯，看看怎么能解决下
