### ISSUE TITLE
Getting Started With TensorFlow

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#20]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/get_started.md)
  * PR 地址：#67
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2+2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by joyking7** [comment]
翻译认领

**Comment by leviding** [comment]
@joyking7 好的
