### ISSUE TITLE
TensorBoard: Graph Visualization

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#21]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/graph_viz.md)
  * PR 地址：#33
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by San-greal** [comment]
翻译认领

**Comment by leviding** [comment]
@San-greal 好的，翻以前请认真看翻译规定

**Comment by San-greal** [comment]
好的

**Comment by San-greal** [comment]
@leviding (｡･∀･)ﾉﾞ嗨，已经翻译好了，我提交了哦。突然发现你是老乡哈哈哈哈。

**Comment by leviding** [comment]
哈哈哈，收到
