### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#22]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/index.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by leviding** [comment]
@XatMassacrE 好的

**Comment by XatMassacrE** [comment]
@leviding 这个文件没找到，是不是和 Getting Started With TensorFlow 这个任务重了啊

**Comment by leviding** [comment]
@XatMassacrE 更新了，你再试试？很少的内容，几分钟翻译好的。
