### ISSUE TITLE
Building Input Functions with tf.estimator

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#23]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/input_fn.md)
  * PR 地址：#95
  ----
  * 翻译时间：8 天
  * 校对时间：3 天
  * 翻译积分：8 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by leviding** [comment]
@changkun 好的

**Comment by leviding** [comment]
@changkun 翻译怎么样啦，小哥超期啦

**Comment by changkun** [comment]
@leviding 额。。彻底把这档事儿给忘了 [捂脸] 马上来

**Comment by leviding** [comment]
@changkun 哈哈哈，别忘了哈

**Comment by changkun** [comment]
@leviding 非常抱歉久等了 ○|￣|_ ref #95

**Comment by leviding** [comment]
@changkun 哈哈，辛苦了
