### ISSUE TITLE
Regression Examples

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#24]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/linear_regression.md)
  * PR 地址：#37
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by leviding** [comment]
@XatMassacrE 好的
