### ISSUE TITLE
TensorBoard: Visualizing Learning

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#25]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/summaries_and_tensorboard.md)
  * PR 地址：#35
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：2 分 南智敏 4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by missmisslonely** [comment]
之前自学有翻译过，报个名

**Comment by leviding** [comment]
@missmisslonely 好的

**Comment by missmisslonely** [comment]
已经发起Pull request
