### ISSUE TITLE
TensorBoard Histogram Dashboard

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#26]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/get_started/tensorboard_histograms.md)
  * PR 地址：#34
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ppp-man** [comment]
翻译认领

**Comment by leviding** [comment]
@ppp-man 好的

**Comment by ppp-man** [comment]
@leviding 忘了留言，补一个翻译完毕

**Comment by leviding** [comment]
2333
