### ISSUE TITLE
请认真看翻译规定再进行翻译，否则将被 close。

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#28]
请认真阅读翻译规则再进行翻译：和这个指南里的区别只是把 xitu/gold-miner 换成 xitu/TensorFlow

教程 : [翻译计划译者教程](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
@leviding 最好可以整理一个专用名词对照表和不翻译单词的表，保证翻译的一致性。

**Comment by leviding** [comment]
整理起成本太高，希望译者能帮忙总结。
