### ISSUE TITLE
Installing TensorFlow for Java

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#4]
* Markdown文件：[Installing TensorFlow for Java](#)
  * PR 地址：#32
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：2.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zcgeng** [comment]
翻译认领

**Comment by leviding** [comment]
@zcgeng 好的
