### ISSUE TITLE
Simple Audio Recognition

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#40]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/audio_recognition.md)
  * PR 地址：#84
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：15 分
  * 校对积分：5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
翻译认领

**Comment by JohnJiangLA** [comment]
@leviding 翻译完成，求加倍
