### ISSUE TITLE
Convolutional Neural Networks

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#41]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/deep_cnn.md)
  * PR 地址：94
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by joyking7** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@joyking7 好的

**Comment by joyking7** [comment]
@leviding 内容比我想象的多，申请延长翻译时间

**Comment by leviding** [comment]
@joyking7 收到

**Comment by leviding** [comment]
@joyking7 怎么样了

**Comment by joyking7** [comment]
@leviding 沉迷课设，还差一部分的修改，争取今天pr。

**Comment by leviding** [comment]
哈哈哈，好
