### ISSUE TITLE
Image Recognition

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#42]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/image_recognition.md)
  * PR 地址：#81
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领
