### ISSUE TITLE
How to Retrain Inception's Final Layer for New Categories

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#43]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/image_retraining.md)
  * PR 地址：#97
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shi-xiaopeng** [comment]
我来翻译吧！
翻译认领 @leviding

**Comment by leviding** [comment]
@shi-xiaopeng 翻译的怎么样了
