### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#44]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/index.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译

**Comment by leviding** [comment]
这篇文章，括号里的内容不翻译哈

**Comment by lsvih** [comment]
卧槽，晚了。。我已经翻完了。。这就改回去

**Comment by leviding** [comment]
2333
