### ISSUE TITLE
A Guide to TF Layers: Building a Convolutional Neural Network

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#46]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/layers.md)
  * PR 地址：
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分 pkuwwt 5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领

**Comment by leviding** [comment]
@edvardHua ok

**Comment by leviding** [comment]
@edvardHua 翻译的怎么样了

**Comment by edvardHua** [comment]
@leviding 这周末提交，最近加班比较严重，耽搁了翻译。

**Comment by leviding** [comment]
@edvardHua 好的

**Comment by edvardHua** [comment]
@leviding 完成翻译啦。PR [在此](https://github.com/xitu/tensorflow/pull/93)
