### ISSUE TITLE
Large-scale Linear Models with TensorFlow

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#47]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/linear.md)
  * PR 地址：#98
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by shi-xiaopeng** [comment]
翻译认领
@leviding

**Comment by leviding** [comment]
@shi-xiaopeng ok
