### ISSUE TITLE
Mandelbrot Set

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#48]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/mandelbrot.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领翻译

**Comment by leviding** [comment]
@lsvih 好的
