### ISSUE TITLE
Partial Differential Equations

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#49]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/pdes.md)
  * PR 地址：#62
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领

**Comment by leviding** [comment]
666
