### ISSUE TITLE
Installing TensorFlow on Ubuntu

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#5]
* Markdown文件：[Installing TensorFlow on Ubuntu](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/install_linux.md)
  * PR 地址：
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：9 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
翻译认领
