### ISSUE TITLE
Using GPUs

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#52]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/using_gpu.md)
  * PR 地址：#64
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分 xiaoxi666 2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by caoyi0905** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@caoyi0905 好的。
