### ISSUE TITLE
TensorFlow Linear Model Tutorial

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#53]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/wide.md)
  * PR 地址：#89
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by caoyi0905** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@caoyi0905 ok

**Comment by leviding** [comment]
@caoyi0905 这还有一篇翻译哈

**Comment by caoyi0905** [comment]
@leviding 今晚交工

**Comment by leviding** [comment]
awesome

**Comment by caoyi0905** [comment]
@leviding 最近比较忙，抱歉了

**Comment by leviding** [comment]
@caoyi0905 Great，提交上来了就好了，辛苦了。
