### ISSUE TITLE
TensorFlow Wide & Deep Learning Tutorial

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#54]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/wide_and_deep.md)
  * PR 地址：#86
  ----
  * 翻译时间：5  天
  * 校对时间：1.5 天
  * 翻译积分：5 分
  * 校对积分：1.5  分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by charsdavy** [comment]
认领翻译 @leviding

**Comment by leviding** [comment]
@charsdavy 好的
