### ISSUE TITLE
Vector Representations of Words

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#55]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/tutorials/word2vec.md)
  * PR 地址：
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by leviding** [comment]
@XatMassacrE ok

**Comment by leviding** [comment]
@XatMassacrE 这篇记得翻译哈

**Comment by XatMassacrE** [comment]
@leviding 恩，正在翻。

**Comment by leviding** [comment]
@XatMassacrE 翻译的好，积分翻倍，有空多认领文章翻译哈。
