### ISSUE TITLE
Installing TensorFlow on macOS

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#6]
* Markdown文件：[Installing TensorFlow on macOS](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/install_mac.md)
  * PR 地址：#15
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
翻译认领

**Comment by Raoul1996** [comment]
校对认领
