### ISSUE TITLE
Importing Data

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#68]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/datasets.md)
  * PR 地址：#114
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
翻译认领

**Comment by leviding** [comment]
@JohnJiangLA ok

**Comment by leviding** [comment]
@JohnJiangLA 翻译的怎么样啦

**Comment by JohnJiangLA** [comment]
不好意思，这几天公司事情有点忙，这周末解决它！

**Comment by leviding** [comment]
好，辛苦了。
