### ISSUE TITLE
Debugging TensorFlow Programs

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#69]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/debugger.md)
  * PR 地址：#122
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3 分 pkuwwt 5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领

**Comment by leviding** [comment]
@edvardHua ok

**Comment by edvardHua** [comment]
完成翻译，[PR122](https://github.com/xitu/tensorflow/pull/122)
