### ISSUE TITLE
Installing TensorFlow from Sources

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#7]
* Markdown文件：[Installing TensorFlow from Sources](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/install_sources.md)
  * PR 地址：#82
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：1.5 分 MRNIU + 1
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by gzponline** [comment]
翻译认领

**Comment by leviding** [comment]
@gzponline 翻译的怎么样了啊

**Comment by gzponline** [comment]
正在翻译  最近在考试 我尽快

**Comment by leviding** [comment]
好的

**Comment by leviding** [comment]
考试结束了吗？翻译怎么样了 @gzponline

**Comment by gzponline** [comment]
还差一点 了 最晚明天

**Comment by gzponline** [comment]
已经提交 pr

**Comment by gzponline** [comment]
修改完成  麻烦看看还有什么问题
