### ISSUE TITLE
Estimators

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#71]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/estimators.md)
  * PR 地址：#99
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by edvardHua** [comment]
翻译认领

**Comment by leviding** [comment]
@edvardHua ok

**Comment by leviding** [comment]
@edvardHua 微信私聊我下，有点事

**Comment by edvardHua** [comment]
完成翻译，[PR在此](https://github.com/xitu/tensorflow/pull/99)
