### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#72]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/faq.md)
  * PR 地址：#85
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by leviding** [comment]
@XatMassacrE ok
