### ISSUE TITLE
Graphs and Sessions

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#73]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/graphs.md)
  * PR 地址：#140
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by JohnJiangLA** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@JohnJiangLA ok！辛苦了

**Comment by Romeo0906** [comment]
这个翻译完了吗 @leviding

**Comment by leviding** [comment]
@Romeo0906 好像没， @JohnJiangLA 这个翻译的怎么样啦

**Comment by JohnJiangLA** [comment]
刚搞完，元旦放假回了一趟老家，耽误了...

**Comment by JohnJiangLA** [comment]
@leviding 交货，耽误久了，干了两年...

**Comment by Romeo0906** [comment]
哈哈，等着给你校对呢 @JohnJiangLA

**Comment by pkuwwt** [comment]
@leviding 校对申请
