### ISSUE TITLE
Programmer's Guide

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#74]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/index.md)
  * PR 地址：
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by MRNIU** [comment]
@leviding 翻译认领

**Comment by JohnJiangLA** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@JohnJiangLA ok！辛苦了
