### ISSUE TITLE
保存和恢复

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#75]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/saved_model.md)
  * PR 地址：#123
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：15 分
  * 校对积分：4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by carriecc** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@carriecc ok
