### ISSUE TITLE
Tensors

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#76]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/tensors.md)
  * PR 地址：#124
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TobiasLee** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@TobiasLee ok

**Comment by TobiasLee** [comment]
@leviding  翻译完成
