### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#77]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/variables.md)
  * PR 地址：#116
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Romeo0906** [comment]
认领翻译，翻译认领

**Comment by leviding** [comment]
@romeo 你的了
