### ISSUE TITLE
TensorFlow Version Compatibility

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#78]
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/programmers_guide/version_compat.md)
  * PR 地址：#91
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：9 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xiaoxi666** [comment]
翻译认领 @LeviDing

**Comment by leviding** [comment]
@xiaoxi666 ok

**Comment by xiaoxi666** [comment]
翻译完成 @leviding
