### ISSUE TITLE
Installing TensorFlow on Windows

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#8]
* Markdown文件：[Installing TensorFlow on Windows](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/install_windows.md)
  * PR 地址：#30
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by elijahxyc** [comment]
翻译认领

**Comment by leviding** [comment]
好的 @elijahxyc  
翻以前看下相应的翻译规范：https://github.com/xitu/gold-miner/wiki

**Comment by elijahxyc** [comment]
翻译已经完成。https://github.com/tensorflow/tensorflow/pull/14362

**Comment by leviding** [comment]
@elijahxyc 你 pull request 错地址了，请认真阅读翻译规则再进行翻译。
https://github.com/xitu/gold-miner/wiki/%E5%85%B3%E4%BA%8E%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E7%BF%BB%E8%AF%91%E4%BB%A5%E5%8F%8A%E5%90%8E%E7%BB%AD%E6%9B%B4%E6%96%B0%E7%9A%84%E6%95%99%E7%A8%8B

和这个指南里的区别只是把 xitu/gold-miner 换成 xitu/TensorFlow
