### ISSUE TITLE
Transitioning to TensorFlow 1.0

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow#9]
* Markdown文件：[Transitioning to TensorFlow 1.0](https://github.com/xitu/tensorflow/blob/f4db3b27430479cccb51518952102d63a3ebc916/tensorflow/docs_src/install/migration.md)
  * PR 地址：#12
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
翻译认领
